name: Build and publish GUI

on:
  push:
    branches: [ v2.0.1 ]
    paths:
      - '.env.k8s'

jobs:
  PackageDeploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup BuildX
        uses: docker/setup-buildx-action@v2

      - name: Load environment variables and set them
        run: |
          if [ -f .env.k8s ]; then
            export $(cat .env.k8s | grep -v '^#' | xargs)
          fi
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "FIX=$FIX" >> $GITHUB_ENV
      - name: Set repo
        run: |
           LOWER_CASE_GITHUB_REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
           echo "DOCKER_TAG_CUSTOM=ghcr.io/${LOWER_CASE_GITHUB_REPOSITORY}:$RELEASE-$VERSION.$BUILD.$FIX" >> $GITHUB_ENV
           echo "$GITHUB_ENV"
      - name: Docker Build
        run: | 
           pwd
           docker image build -f Dockerfile.k8s --tag $DOCKER_TAG_CUSTOM .

      - name: Log in to GitHub container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push Docker image to ghcr
        run: docker push $DOCKER_TAG_CUSTOM
